[pytest]
pythonpath = . src
filterwarnings =
    error
    ignore::UserWarning
    ignore:function ham\(\) is deprecated:DeprecationWarning

asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
